# Terminal & System Settings
set -g default-terminal "tmux-256color"
set -sa terminal-features ',alacritty:RGB:usstyle'
set -g mouse on
set -s escape-time 0
set -g status-interval 1

# Window & Pane Numbering
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Keybindings: Window & Pane Management
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
bind r source-file ~/.tmux.conf \; display "config reloaded"

# Titles, Status, & Session Menus
setw -g automatic-rename-format "#{pane_current_command} @ #{b:pane_current_path}"
set -g set-titles on
set -g set-titles-string "#{pane_current_command} @ #{b:pane_current_path}"
bind s choose-tree -Zs -f "#{&&:#{window_active},#{pane_active}}" -F "#{pane_current_command} @ #{b:pane_current_path}"
bind S run-shell -C "display-menu -T Sessions #{S:\"#{pane_current_command} @ #{b:pane_current_path}\" \"\" \"switch-client -t '#{session_id}'\" }"

# Plugin Manager (TPM)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
run '~/.tmux/plugins/tpm/tpm'
