# General & Environment
set -g default-terminal "tmux-256color"
set-option -sa terminal-features ',alacritty:RGB'
set-option -ga terminal-features ",alacritty:usstyle"
set -g mouse on
set -s escape-time 0

# Display & Indexing
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set-option -g status-interval 1

# Automation & Hooks
set-hook -g pane-focus-in 'run-shell "tmux rename-session \"#{pane_current_command} @ #{b:pane_current_path}\" "'
set-hook -g session-window-changed 'run-shell "tmux rename-session \"#{pane_current_command} @ #{b:pane_current_path}\" "'

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize TPM (must remain at the bottom)
run '~/.tmux/plugins/tpm/tpm'
