# Alacritty-Specific Color & Feature Fixes
# Set the terminal inside tmux to support 256 colors and italics
set -g default-terminal "tmux-256color"
# Tell tmux that the outer terminal (Alacritty) supports True Color (RGB)
set-option -sa terminal-features ',alacritty:RGB'
# Enable modern undercurl & underline styling inside tmux for Alacritty
set-option -ga terminal-features ",alacritty:usstyle"

# Enable mouse: click panes, resize panes, select text, scroll
set -g mouse on

# Sane indexing (start at 1 instead of 0)
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
